package es.udc.cartolab.gvsig.epanet;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import es.udc.cartolab.gvsig.epanet.network.EpanetWrapper;
import es.udc.cartolab.gvsig.epanet.utils.ComparatorUtils;
import es.udc.cartolab.gvsig.epanet.utils.TestProperties;

/**
 * 
 * Checks that the result file generated by epanet for a given input file is the
 * same that a gold file
 * 
 * This is useful to check if a inp generated with the plugin that is expected
 * to be equals to a inp gold file, produces a result file equals to the result
 * gold file
 * 
 */
public class EpanetWrapperTest {

    private static EpanetWrapper epanet;

    @Rule
    public TemporaryFolder temp = new TemporaryFolder();

    @BeforeClass
    public static void setUpBeforeClass() {
	epanet = new EpanetWrapper(TestProperties.epanetPath);
    }

    @Test
    public void reportIsGenerated() throws IOException {
	final String inpPath = "fixtures/one_junction.inp";
	final File copy = copyToTemp(inpPath);
	final String[] rptPath = epanet.execute(copy.getAbsolutePath());
	final File rpt = new File(rptPath[0]);
	assertEquals(rpt.getName(), "one_junction.rpt");
	assertTrue(rpt.exists());
    }

    private File copyToTemp(final String path) throws IOException {
	final File org = new File(path);
	FileUtils.copyFileToDirectory(org, temp.getRoot());
	return FileUtils.getFile(temp.getRoot(), org.getName());
    }

    @Test
    public void oneJunction() throws Exception {
	final File expectedRPT = new File("fixtures/one_junction.rpt");
	final String inpPath = "fixtures/one_junction.inp";
	final File copy = copyToTemp(inpPath);

	String actualRPT[] = epanet.execute(copy.getAbsolutePath());
	assertTrue(ComparatorUtils.rptComparator(expectedRPT, new File(actualRPT[0])));
    }

    @Test
    public void net1() throws Exception {
	final File expectedRPT = new File("fixtures/Net1.rpt");
	final String inpPath = "fixtures/Net1.inp";
	final File copy = copyToTemp(inpPath);
	String actualRPT[] = epanet.execute(copy.getAbsolutePath());
	assertTrue(ComparatorUtils.rptComparator(expectedRPT, new File(actualRPT[0])));
    }

    @Test
    public void net2() throws Exception {
	final File expectedRPT = new File("fixtures/Net2.rpt");
	final String inpPath = "fixtures/Net2.inp";
	final File copy = copyToTemp(inpPath);
	String actualRPT[] = epanet.execute(copy.getAbsolutePath());
	assertTrue(ComparatorUtils.rptComparator(expectedRPT, new File(actualRPT[0])));
    }
}
